# Generated by Django 4.1 on 2022-08-21 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assesment', '0004_assesment_time_per_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('should_finish_before', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('assesment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assesment.assesment')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attempt.attempt')),
                ('chosen_chioce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assesment.choice')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assesment.question')),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='questions',
            field=models.ManyToManyField(through='attempt.QuestionAnswer', to='assesment.question'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
